"""rename_message_id_to_telegram_message_id

Revision ID: 84176aa2e975
Revises: c17982a24b3a
Create Date: 2026-06-04 16:24:17.031274

Migration 39525caf8b08 was committed as a no-op stub, so the DB still has
history.message_id (identity PK) instead of history.telegram_message_id
(composite PK with chat_id). This migration performs the actual rename and
PK change.
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84176aa2e975'
down_revision: Union[str, None] = 'c17982a24b3a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # Drop the auto-generated identity PK on message_id.
    op.drop_constraint("history_pkey", "history", type_="primary")

    # Rename the column.
    op.alter_column("history", "message_id", new_column_name="telegram_message_id")

    # Strip the IDENTITY property so the column is a plain BigInteger.
    op.execute("ALTER TABLE history ALTER COLUMN telegram_message_id DROP IDENTITY IF EXISTS")

    # Composite PK: (chat_id, telegram_message_id) — mirrors the ORM model.
    op.create_primary_key("history_pkey", "history", ["chat_id", "telegram_message_id"])


def downgrade() -> None:
    op.drop_constraint("history_pkey", "history", type_="primary")

    op.alter_column("history", "telegram_message_id", new_column_name="message_id")

    op.execute(
        "ALTER TABLE history ALTER COLUMN message_id ADD GENERATED BY DEFAULT AS IDENTITY"
    )

    op.create_primary_key("history_pkey", "history", ["message_id"])
