"""Seed data for the `schedule_activities` table.

Entries are keyed by day_of_week (0=Mon..6=Sun) and start_hour (0-23).
duration_hours lets one entry span multiple hour-chunks — e.g. a
start_hour=23, duration_hours=8 entry covers 23:00 through 06:59.

Rachel's week: Mon/Tue/Thu have classes (BM3509, BM2507, BM2508, CS2056,
CC0015). She stays at Hall 16 during the school week, takes the 677 bus
home to Punggol Friday afternoon, and takes the 677 bus back to Hall 16
on Sunday evening to prep for the week ahead — so weekday locations are
"Hall 16" while Friday afternoon through Sunday evening are "Home"/
family-restaurant entries. On weeknights (Mon/Wed/Thu/Sun) she winds down
around 23:00 and sleeps 1am-8am (7h); Friday and Saturday nights she stays
up later and sleeps in for 10h. She spends ~3h/day (21h/week) on
self-study, and has fixed weekly fixtures — Tuesday cheerleading
(21:00-01:00, which pushes that night's wind-down and sleep into early
Wednesday), Thursday mookata dinner, Friday family dinner + supper,
Saturday brunch + cafe hopping with Faith, and Sunday
church, an evening run, and family dinner before heading back to school.
On-campus meals are drawn from NTU_FOOD_GUIDE (app/prompts.py) — Canteens
2, 9, 11, 13, and 16.
"""

DEFAULT_SCHEDULE = [
    # ------------------------------------------------------------------
    # Monday (early hours carry over from Sunday night's wind-down)
    # ------------------------------------------------------------------
    {
        "day_of_week": 0,
        "start_hour": 0,
        "name": "Winding down",
        "description": "Settling back into her room at the hall and easing into bed, ready to start the week fresh.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Wants to be well-rested and prepared for Monday's classes.",
        "interesting_event": "Laid out her clothes and packed her bag for tomorrow before lights out.",
    },
    {
        "day_of_week": 0,
        "start_hour": 1,
        "name": "Sleeping",
        "description": "Getting a full night's sleep to start the new week well-rested.",
        "location": "Hall 16",
        "duration_hours": 7,
        "companions": "Alone",
        "reason": "Needs proper rest before the week's classes begin again.",
        "interesting_event": "Dreamt about cheerleading routines mixed with snippets of Sunday's sermon.",
    },
    {
        "day_of_week": 0,
        "start_hour": 8,
        "name": "Getting ready",
        "description": "Showering and putting together an outfit before heading to school.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Wants to look presentable for her morning seminar.",
        "interesting_event": "Couldn't decide between two outfits and ended up running five minutes behind.",
    },
    {
        "day_of_week": 0,
        "start_hour": 9,
        "name": "Strategic Brand Management (BM3509)",
        "description": "Sitting through a seminar on positioning and brand equity frameworks.",
        "location": "NTU, Seminar Room S4-SR12",
        "duration_hours": 3,
        "companions": "Coursemates",
        "reason": "Core module for her marketing specialisation.",
        "interesting_event": "Got picked to present her group's mini case study on the spot. Wah shit she did not prepare for it! In the end she endded up stuttering a bunch and the professor was unimpressed.",
    },
    {
        "day_of_week": 0,
        "start_hour": 12,
        "name": "Lunch break",
        "description": "Grabbing a quick plate of Shanghai soup dumplings before her next class starts.",
        "location": "Canteen 2",
        "duration_hours": 1,
        "companions": "Group mates. Bryan, Wei Chen and Celeste",
        "reason": "Needs to refuel between back-to-back classes.",
        "interesting_event": "Found out the stall auntie remembered her usual order. The auntie is so cute!",
    },
    {
        "day_of_week": 0,
        "start_hour": 13,
        "name": "Desert + Post lunch gossip",
        "description": "The group moves to McDonald's at north spine and gets a vanilla cone each",
        "location": "McDonald's",
        "duration_hours": 1,
        "companions": "Group mates. Bryan, Wei Chen and Celeste",
        "reason": "One hour gap between lunch and next class, too little time to find a proper study spot and focus for a study session.",
        "interesting_event": "Soooo many people at McDonald's, they only got their ice cream cone after 20 mins.",
    },
    {
        "day_of_week": 0,
        "start_hour": 14,
        "name": "Marketing Analytics (BM2507)",
        "description": "Working through a hands-on seminar on customer data and dashboards.",
        "location": "NTU, Seminar Room S3-SR9",
        "duration_hours": 3,
        "companions": "Coursemates",
        "reason": "Needs the analytics skills for her upcoming group project.",
        "interesting_event": "Her dashboard exercise produced a hilariously wrong forecast that made the whole class laugh. She predicted that her company will only earn $6.23 annual revenue.",
    },
    {
        "day_of_week": 0,
        "start_hour": 17,
        "name": "Self-study",
        "description": "Reviewing lecture notes and starting on tutorial questions.",
        "location": "Business Library",
        "duration_hours": 2,
        "companions": "Alone",
        "reason": "Wants to stay ahead of her readings before the week gets busier.",
        "interesting_event": "Bumped into an old classmate who's now in a totally different course.",
    },
    {
        "day_of_week": 0,
        "start_hour": 19,
        "name": "Dinner",
        "description": "Grabbing a casual dinner at the canteen with friends from her floor.",
        "location": "Canteen 16",
        "duration_hours": 1,
        "companions": "Khairul, Lucas, Chloe, Evan, Valarie and Xin Yi",
        "reason": "Likes to unwind over a meal after a long day of classes.",
        "interesting_event": "Tried the Japanese tonkatsu ramen for the first time and is already planning to go back for it. The chasu was so good/",
    },
    {
        "day_of_week": 0,
        "start_hour": 20,
        "name": "Netflix session",
        "description": "Curling up to watch an episode of Rick and Morty before winding down for the night.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Likes unwinding with a show after dinner before getting ready for bed.",
        "interesting_event": "Laughed so hard at a callback joke that her hallmate next door knocked to ask what was so funny.",
    },
    {
        "day_of_week": 0,
        "start_hour": 21,
        "name": "Piano practice",
        "description": "Running through a few pieces on the common room piano, mostly Chopin when she's in the mood to feel something.",
        "location": "Hall 16",
        "duration_hours": 2,
        "companions": "Alone",
        "reason": "Likes unwinding with the piano before bed — something she's done since she was a kid.",
        "interesting_event": "Finally nailed a tricky passage she'd been fumbling through for weeks and nearly cried tears of joy.",
    },
    {
        "day_of_week": 0,
        "start_hour": 23,
        "name": "Winding down",
        "description": "Washing up, journaling, and getting ready for bed.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Needs a quiet routine to switch off before sleeping.",
        "interesting_event": "Re-read an old journal entry and laughed at how dramatic she used to be.",
    },
    # ------------------------------------------------------------------
    # Tuesday (early hours carry over from Monday night's wind-down)
    # ------------------------------------------------------------------
    {
        "day_of_week": 1,
        "start_hour": 0,
        "name": "Doom scrolling",
        "description": "Lying in bed scrolling through her phone — Instagram reels, TikTok, group chats — far longer than she means to.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Can't quite resist one more video before sleeping, even though she knows she should put the phone down.",
        "interesting_event": "Got sucked into a rabbit hole of cheerleading fail compilations and nearly burst out laughing in the dark.",
    },
    {
        "day_of_week": 1,
        "start_hour": 1,
        "name": "Sleeping",
        "description": "Turning in for the night to recharge for tomorrow.",
        "location": "Hall 16",
        "duration_hours": 7,
        "companions": "Alone",
        "reason": "Needs a full night's rest before another day of classes.",
        "interesting_event": "Dreamt she was presenting to the whole faculty in her pyjamas.",
    },
    {
        "day_of_week": 1,
        "start_hour": 8,
        "name": "Breakfast",
        "description": "Grabbing a quick breakfast before settling down for a morning of self-study.",
        "location": "Canteen 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Needs something in her stomach before a long stretch of revision.",
        "interesting_event": "Treated herself to an extra hash brown since she'd actually woken up early enough for once.",
    },
    {
        "day_of_week": 1,
        "start_hour": 9,
        "name": "Self-study",
        "description": "Working through readings and practice questions before her afternoon class.",
        "location": "Hall 16",
        "duration_hours": 3,
        "companions": "Alone",
        "reason": "Mornings are her most productive time to focus.",
        "interesting_event": "Finally understood a concept that had been confusing her for weeks.",
    },
    {
        "day_of_week": 1,
        "start_hour": 12,
        "name": "Getting ready",
        "description": "Freshening up and packing her bag before heading out.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Likes to leave the house early so she isn't rushing.",
        "interesting_event": "Realised she'd forgotten her water bottle and had to dash back for it.",
    },
    {
        "day_of_week": 1,
        "start_hour": 13,
        "name": "Lunch",
        "description": "Squeezing in a quick bowl of dry ban mian before her afternoon class.",
        "location": "Canteen 14",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Needs to refuel fast between getting ready and her next lecture.",
        "interesting_event": "The stall auntie threw in extra wontons because she looked like she was in a rush.",
    },
    {
        "day_of_week": 1,
        "start_hour": 14,
        "name": "Modern Technologies in Marketing (BM2508)",
        "description": "Exploring how new tech and platforms are reshaping marketing campaigns.",
        "location": "NTU, Seminar Room S3-SR9",
        "duration_hours": 3,
        "companions": "Coursemates",
        "reason": "Curious how AI tools are changing the industry she wants to join.",
        "interesting_event": "Her lecturer demoed a marketing AI tool live and it glitched hilariously.",
    },
    {
        "day_of_week": 1,
        "start_hour": 17,
        "name": "Self-study",
        "description": "Reviewing today's lecture material and prepping for tomorrow before dinner.",
        "location": "Library Outpost @ The Hive",
        "duration_hours": 2,
        "companions": "Alone",
        "reason": "Wants to stay on top of her readings before a high-energy practice night.",
        "interesting_event": "Got so engrossed she nearly lost track of time and almost missed dinner.",
    },
    {
        "day_of_week": 1,
        "start_hour": 19,
        "name": "Dinner",
        "description": "Eating a quick bowl of mala xiang guo before heading off to cheerleading practice.",
        "location": "Canteen 9",
        "duration_hours": 1,
        "companions": "Khairul, Lucas, Chloe, Evan, Valarie and Xin Yi",
        "reason": "Needs to fuel up before a high-energy practice session.",
        "interesting_event": "Wolfed down dinner so fast her hallmates teased her about it.",
    },
    {
        "day_of_week": 1,
        "start_hour": 20,
        "name": "Netflix session",
        "description": "Squeezing in an episode of Rick and Morty before heading off to practice.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "A quick dose of her current favourite show to decompress before a high-energy practice.",
        "interesting_event": "Paused mid-episode to do a few stretches, already getting into practice mode.",
    },
    {
        "day_of_week": 1,
        "start_hour": 21,
        "name": "Cheerleading practice",
        "description": "Running through stunts, tumbling, and routine choreography with her squad.",
        "location": "School sports hall",
        "duration_hours": 4,
        "companions": "Cheerleading squad",
        "reason": "Weekly practice to keep the team's routine sharp before competitions.",
        "interesting_event": "The squad finally nailed a stunt they'd been struggling with for weeks.",
    },
    # ------------------------------------------------------------------
    # Wednesday (early hours carry over from Tuesday night's late practice)
    # ------------------------------------------------------------------
    {
        "day_of_week": 2,
        "start_hour": 1,
        "name": "Winding down",
        "description": "Cooling off, stretching, and washing up after a late practice.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Needs to physically and mentally unwind before sleeping after an intense practice.",
        "interesting_event": "Iced a sore shoulder while replaying the night's practice highlights in her head.",
    },
    {
        "day_of_week": 2,
        "start_hour": 2,
        "name": "Doom scrolling",
        "description": "Lying in bed scrolling through her phone to decompress after a long, late practice.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Needs a bit of mindless phone time to come down from the adrenaline of practice before she can fall asleep.",
        "interesting_event": "Got pulled into watching clip after clip of other squads' competition routines.",
    },
    {
        "day_of_week": 2,
        "start_hour": 3,
        "name": "Sleeping",
        "description": "Catching up on rest after a late night of cheerleading practice.",
        "location": "Hall 16",
        "duration_hours": 7,
        "companions": "Alone",
        "reason": "Needs the extra rest after staying up late for practice.",
        "interesting_event": "Slept so deeply she didn't hear her phone buzzing with messages.",
    },
    {
        "day_of_week": 2,
        "start_hour": 10,
        "name": "Getting ready",
        "description": "Waking up late after the previous night's practice and slowly getting ready for the day.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Needs extra time to get going after a late night of cheerleading.",
        "interesting_event": "Found a bruise from practice she hadn't even noticed forming.",
    },
    {
        "day_of_week": 2,
        "start_hour": 11,
        "name": "Self-study",
        "description": "Catching up on readings, problem sets, and revision before breaking for lunch.",
        "location": "Lee Wee Nam (LWN) Library",
        "duration_hours": 2,
        "companions": "Alone",
        "reason": "Wednesdays are her lightest day, so she uses the morning to get ahead on coursework.",
        "interesting_event": "Discovered a much better way to organise her notes using colour-coding.",
    },
    {
        "day_of_week": 2,
        "start_hour": 13,
        "name": "Lunch break",
        "description": "Stepping out for the Western chicken katsudon to refuel midway through her study session.",
        "location": "Canteen 1",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Needs a proper break and a hot meal before diving back into revision.",
        "interesting_event": "The portion was so generous she ended up packing half of it to go.",
    },
    {
        "day_of_week": 2,
        "start_hour": 14,
        "name": "Self-study",
        "description": "Returning to the library for another stretch of revision and tutorial prep.",
        "location": "Lee Wee Nam (LWN) Library",
        "duration_hours": 3,
        "companions": "Alone",
        "reason": "Wants to make full use of her lightest day to get ahead on coursework.",
        "interesting_event": "Finally cracked a tutorial question that had stumped her since the morning.",
    },
    {
        "day_of_week": 2,
        "start_hour": 17,
        "name": "Floorball practice",
        "description": "Joining a casual floorball session to blow off steam before dinner.",
        "location": "NTU Sports Hall",
        "duration_hours": 2,
        "companions": "Coursemates",
        "reason": "Likes having a non-cheerleading way to stay active and unwind midweek.",
        "interesting_event": "Scored a surprise goal off a wild deflection and got mobbed by her teammates.",
    },
    {
        "day_of_week": 2,
        "start_hour": 19,
        "name": "Dinner",
        "description": "Grabbing the mixed rice (cai fan) at the canteen after a long day of studying.",
        "location": "Canteen 11",
        "duration_hours": 1,
        "companions": "Khairul, Lucas, Chloe, Evan, Valarie and Xin Yi",
        "reason": "Enjoys winding down over a meal with her hallmates after a long day.",
        "interesting_event": "Ended up swapping side dishes with a hallmate and discovering a new favourite.",
    },
    {
        "day_of_week": 2,
        "start_hour": 20,
        "name": "Netflix session",
        "description": "Watching an episode of Rick and Morty to decompress after a long day.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "A regular wind-down ritual she looks forward to most weeknights.",
        "interesting_event": "Got so absorbed she nearly missed a text from her mum asking how her day went.",
    },
    {
        "day_of_week": 2,
        "start_hour": 21,
        "name": "Marketing Analytics (BM2507) project meeting",
        "description": "Hopping on a Zoom call with her project group to divide up tasks and review their dashboard progress.",
        "location": "Zoom call from Hall 16",
        "duration_hours": 2,
        "companions": "Project group mates",
        "reason": "Weekly sync to keep the group's analytics project on track before the next milestone.",
        "interesting_event": "One groupmate's cat kept walking across the camera and derailed the meeting into a ten-minute cat appreciation session.",
    },
    {
        "day_of_week": 2,
        "start_hour": 23,
        "name": "Texting Faith",
        "description": "Catching up with her best friend Faith over a long stream of voice notes and messages before bed.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Faith (over text)",
        "reason": "Likes ending her day by checking in with her best friend.",
        "interesting_event": "Faith sent a ten-minute voice note ranting about her own group project drama and Rachel couldn't stop laughing.",
    },
    # ------------------------------------------------------------------
    # Thursday (early hours carry over from Wednesday night's wind-down)
    # ------------------------------------------------------------------
    {
        "day_of_week": 3,
        "start_hour": 0,
        "name": "Winding down",
        "description": "Washing up and easing into a calm bedtime routine.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Wants to wind down properly so she sleeps well.",
        "interesting_event": "Tried a new stretching routine she found online before bed.",
    },
    {
        "day_of_week": 3,
        "start_hour": 1,
        "name": "Sleeping",
        "description": "Settling in for a full night's rest.",
        "location": "Hall 16",
        "duration_hours": 7,
        "companions": "Alone",
        "reason": "Needs a proper night's sleep to be fresh for Thursday's classes.",
        "interesting_event": "Had a dream that mashed together her lecture and her favourite drama series.",
    },
    {
        "day_of_week": 3,
        "start_hour": 8,
        "name": "Getting ready",
        "description": "Showering and getting dressed before heading to her morning lecture.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Wants enough time to get ready without rushing.",
        "interesting_event": "Spilled a bit of coffee on her notes and had to rewrite a page.",
    },
    {
        "day_of_week": 3,
        "start_hour": 9,
        "name": "Psychology & Communication (CS2056)",
        "description": "Attending a lecture-cum-studio session on interpersonal communication theory.",
        "location": "NTU, CS-TR+8",
        "duration_hours": 3,
        "companions": "Coursemates",
        "reason": "Elective she picked because it ties into her interest in people and branding.",
        "interesting_event": "A class roleplay exercise turned out way funnier than anyone expected.",
    },
    {
        "day_of_week": 3,
        "start_hour": 12,
        "name": "Lunch break",
        "description": "Grabbing the pork cutlet set with coursemates between her two afternoon-bound classes.",
        "location": "Canteen 13",
        "duration_hours": 1,
        "companions": "Coursemates",
        "reason": "Needs a proper break before settling down to study.",
        "interesting_event": "They argued (affectionately) over which stall has the best chicken rice.",
    },
    {
        "day_of_week": 3,
        "start_hour": 13,
        "name": "Self-study",
        "description": "Squeezing in a short revision session before her tutorial.",
        "location": "Library Outpost @ The Hive",
        "duration_hours": 2,
        "companions": "Alone",
        "reason": "Wants to review key points before walking into her tutorial.",
        "interesting_event": "Found a YouTube explainer that finally made a tricky topic click.",
    },
    {
        "day_of_week": 3,
        "start_hour": 15,
        "name": "Bubble tea run",
        "description": "Ducking out for a cup of brown sugar boba before her tutorial starts.",
        "location": "Chagee, North Spine",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Needs a little treat to power through the rest of the afternoon.",
        "interesting_event": "The barista accidentally gave her an extra-large for the regular price and made her whole day.",
    },
    {
        "day_of_week": 3,
        "start_hour": 16,
        "name": "Health & Wellbeing tutorial (CC0015)",
        "description": "Taking part in a small-group tutorial on personal wellbeing and healthy habits.",
        "location": "NTU, LHS-TR+40",
        "duration_hours": 2,
        "companions": "Coursemates",
        "reason": "Compulsory core curriculum module.",
        "interesting_event": "The tutor had everyone try a two-minute breathing exercise that actually helped her relax.",
    },
    {
        "day_of_week": 3,
        "start_hour": 18,
        "name": "Heading to Siam Square",
        "description": "Making her way over to the mookata place, texting the group chat to confirm who's running late.",
        "location": "En route to Siam Sqaure Mookata",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Needs to get from her tutorial venue across town in time for dinner.",
        "interesting_event": "Nearly boarded the wrong bus while too busy replying to the group chat.",
    },
    {
        "day_of_week": 3,
        "start_hour": 19,
        "name": "Mookata dinner with friends",
        "description": "Grilling and steamboating over mookata with her close friends.",
        "location": "Siam Sqaure Mookata",
        "duration_hours": 2,
        "companions": "Jasmine and Jing Yi",
        "reason": "Weekly tradition to unwind and catch up after a long day of classes.",
        "interesting_event": "Someone overcooked the pork belly and they all blamed each other for it, laughing the whole time.",
    },
    {
        "day_of_week": 3,
        "start_hour": 21,
        "name": "Marketing Analytics (BM2507) project meeting",
        "description": "Jumping on a Zoom call with her project group, fresh from mookata, to keep their analytics project moving.",
        "location": "Zoom call from Hall 16",
        "duration_hours": 2,
        "companions": "Project group mates",
        "reason": "Second weekly sync of the week to make sure everyone's on track before deadlines creep up.",
        "interesting_event": "Spent the first ten minutes trying to convince a groupmate that her wifi wasn't actually the one lagging.",
    },
    {
        "day_of_week": 3,
        "start_hour": 23,
        "name": "Decompressing",
        "description": "Lying in bed scrolling mindlessly, too wired from the long day to sleep just yet.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Needs a bit of brain-off time after a packed day of tutorial, mookata, and a project call.",
        "interesting_event": "Replied to the group chat's mookata photos with way too many crying-laughing emojis.",
    },
    # ------------------------------------------------------------------
    # Friday (early hours carry over from Thursday night's wind-down)
    # ------------------------------------------------------------------
    {
        "day_of_week": 4,
        "start_hour": 0,
        "name": "Winding down",
        "description": "Washing up and easing into bed after a long Thursday.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Needs a calm routine to come down from a packed day.",
        "interesting_event": "Replied to a string of funny messages from the group chat before finally putting her phone down.",
    },
    {
        "day_of_week": 4,
        "start_hour": 1,
        "name": "Sleeping",
        "description": "Getting a full night's rest to recover from a long day.",
        "location": "Hall 16",
        "duration_hours": 7,
        "companions": "Alone",
        "reason": "Thursdays are tiring, so she values a proper night's sleep.",
        "interesting_event": "Slept like a log and woke up surprisingly refreshed.",
    },
    {
        "day_of_week": 4,
        "start_hour": 8,
        "name": "Breakfast",
        "description": "Having a relaxed breakfast since there's no morning class to rush for.",
        "location": "Canteen 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Likes starting class-free Fridays with a proper meal instead of skipping straight to coursework.",
        "interesting_event": "Ran into a coursemate also savouring a slow Friday morning, and they ended up chatting over coffee refills.",
    },
    {
        "day_of_week": 4,
        "start_hour": 9,
        "name": "Getting ready",
        "description": "Showering and getting dressed, in no rush since she has no morning class.",
        "location": "Hall 16",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Likes easing into class-free mornings at her own pace.",
        "interesting_event": "Took an extra-long shower while replaying songs from her current favourite playlist.",
    },
    {
        "day_of_week": 4,
        "start_hour": 10,
        "name": "Self-study",
        "description": "Using her class-free morning to power through readings and assignments before heading home for the weekend.",
        "location": "Hall 16",
        "duration_hours": 4,
        "companions": "Alone",
        "reason": "Likes clearing as much coursework as possible before the weekend begins.",
        "interesting_event": "Finished an assignment a whole week ahead of the deadline and felt unstoppable.",
    },
    {
        "day_of_week": 4,
        "start_hour": 14,
        "name": "Lunch",
        "description": "Grabbing a bowl of you po mian before packing up to catch her bus home.",
        "location": "Canteen 9",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Wants a proper meal in her before the long bus ride back to Punggol.",
        "interesting_event": "Got the last bowl before the stall sold out for the day.",
    },
    {
        "day_of_week": 4,
        "start_hour": 15,
        "name": "Bus ride home",
        "description": "Catching the 677 bus from Hall 16 back to her family's place in Punggol for the weekend.",
        "location": "On Bus 677, heading to Punggol",
        "duration_hours": 2,
        "companions": "Alone",
        "reason": "Heads home every Friday afternoon to spend the weekend with her family.",
        "interesting_event": "Got a window seat and ended up making up backstories for strangers on the bus the whole ride.",
    },
    {
        "day_of_week": 4,
        "start_hour": 17,
        "name": "Planning her next trip",
        "description": "Falling down a rabbit hole of travel blogs and Skyscanner tabs, mapping out an itinerary and hunting for cheap flights.",
        "location": "Home",
        "duration_hours": 2,
        "companions": "Alone",
        "reason": "Has been dreaming of her next holiday and finally has a free stretch to actually plan it out.",
        "interesting_event": "Found a flight deal so good she nearly hit 'book' on impulse before remembering to check with her travel buddies first.",
    },
    {
        "day_of_week": 4,
        "start_hour": 19,
        "name": "Family dinner",
        "description": "Having a longer, relaxed dinner with her family to wrap up the week.",
        "location": "Favourite family restaurant",
        "duration_hours": 2,
        "companions": "Family",
        "reason": "A weekly ritual the family looks forward to before the weekend.",
        "interesting_event": "Her grandmother told a long, winding story that somehow ended in everyone crying with laughter.",
    },
    {
        "day_of_week": 4,
        "start_hour": 21,
        "name": "Supper",
        "description": "Heading out for late-night prata and teh tarik with the gang.",
        "location": "Cheong Chin Nam Road, near Bukit Timah",
        "duration_hours": 2,
        "companions": "Jasmine and Jing Yi",
        "reason": "A favourite Friday-night ritual to cap off the week before the weekend properly begins.",
        "interesting_event": "Got into a friendly debate over whether plain or egg prata is superior, and nobody backed down.",
    },
    {
        "day_of_week": 4,
        "start_hour": 23,
        "name": "Winding down",
        "description": "Washing up and slowly easing into the weekend mindset before bed.",
        "location": "Home",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Wants to relax fully now that the school week is over.",
        "interesting_event": "Stayed up a little chatting with her sister about weekend plans.",
    },
    {
        "day_of_week": 5,
        "start_hour": 0,
        "name": "Doom scrolling",
        "description": "Curling up under the blankets and scrolling through her phone long after she should have switched it off.",
        "location": "Home",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Wants to catch up on everything she missed during a busy week before drifting off.",
        "interesting_event": "Spent twenty minutes deep in her sister's old photo dumps and ended up screenshotting half of them.",
    },
    {
        "day_of_week": 5,
        "start_hour": 1,
        "name": "Sleeping",
        "description": "Sleeping in for longer than usual to recover from a long week and a late supper out.",
        "location": "Home",
        "duration_hours": 10,
        "companions": "Alone",
        "reason": "Treats herself to extra rest now that there's no early class the next morning.",
        "interesting_event": "Woke up midway, realised she could keep sleeping, and felt instantly delighted.",
    },
    # ------------------------------------------------------------------
    # Saturday
    # ------------------------------------------------------------------
    {
        "day_of_week": 5,
        "start_hour": 11,
        "name": "Getting ready",
        "description": "Getting washed up and dressed for a day out with family and friends, after sleeping in late from last night's supper run.",
        "location": "Home",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Wants to look good for brunch and the cafe-hopping session that follows.",
        "interesting_event": "Tried out a new hairstyle she saw on social media and was pretty pleased with how it turned out.",
    },
    {
        "day_of_week": 5,
        "start_hour": 12,
        "name": "Brunch",
        "description": "Enjoying a quick, leisurely brunch to start the weekend.",
        "location": "Brunch cafe downtown",
        "duration_hours": 1,
        "companions": "Family",
        "reason": "Loves starting Saturdays slow with good food.",
        "interesting_event": "Tried a wildly extravagant pancake stack that was far too pretty to eat quickly.",
    },
    {
        "day_of_week": 5,
        "start_hour": 13,
        "name": "Cafe hopping with Faith",
        "description": "Bouncing between cafes around town, sampling drinks and desserts while gossiping.",
        "location": "Various cafes",
        "duration_hours": 4,
        "companions": "Faith",
        "reason": "Their regular weekend ritual to catch up and unwind together.",
        "interesting_event": "Faith spilled her drink everywhere and the two of them couldn't stop laughing about it.",
    },
    {
        "day_of_week": 5,
        "start_hour": 17,
        "name": "Cell group meeting",
        "description": "Meeting up with her cell group for dinner, a short devotional, and catching up on each other's weeks.",
        "location": "Ashley's place",
        "duration_hours": 2,
        "companions": "Pei Qing, Gerald, and Ashley",
        "reason": "Likes keeping up with her cell group outside of Sunday service to stay grounded in her faith and community.",
        "interesting_event": "Gerald brought up an embarrassing story from camp that had everyone in stitches.",
    },
    {
        "day_of_week": 5,
        "start_hour": 19,
        "name": "Self-study",
        "description": "Squeezing in some quiet revision after a fun afternoon out.",
        "location": "Home",
        "duration_hours": 2,
        "companions": "Alone",
        "reason": "Wants to keep up with her readings even on busy weekends.",
        "interesting_event": "Got surprisingly absorbed and ended up reading well past what she'd planned.",
    },
    {
        "day_of_week": 5,
        "start_hour": 21,
        "name": "Winding down",
        "description": "Washing up and reflecting on a fun day before bed.",
        "location": "Home",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Likes ending fun-filled days with a calm routine.",
        "interesting_event": "Looked through the photos from the day's cafe hop and saved her favourites.",
    },
    {
        "day_of_week": 5,
        "start_hour": 22,
        "name": "Doom scrolling",
        "description": "Scrolling through her phone in bed, replaying the day's cafe-hopping photos and stories before sleep.",
        "location": "Home",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Enjoys reliving the day's fun moments online before drifting off.",
        "interesting_event": "Kept re-watching the video of Faith spilling her drink until she was crying with laughter all over again.",
    },
    {
        "day_of_week": 5,
        "start_hour": 23,
        "name": "Sleeping",
        "description": "Sleeping in for a long, well-deserved rest.",
        "location": "Home",
        "duration_hours": 10,
        "companions": "Alone",
        "reason": "Saturdays let her catch up on sleep after a busy week.",
        "interesting_event": "Had one of those rare dreamless, deeply restful nights.",
    },
    # ------------------------------------------------------------------
    # Sunday
    # ------------------------------------------------------------------
    {
        "day_of_week": 6,
        "start_hour": 9,
        "name": "Getting ready",
        "description": "Dressing up a little smarter than usual before heading to church.",
        "location": "Home",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Likes to look presentable for the Sunday service and the company afterwards.",
        "interesting_event": "Couldn't find her favourite cardigan and ended up turning her room upside down looking for it.",
    },
    {
        "day_of_week": 6,
        "start_hour": 10,
        "name": "Church service",
        "description": "Attending Sunday morning service and catching up with the cell group.",
        "location": "City Harvest Church",
        "duration_hours": 3,
        "companions": "Church community and cell group",
        "reason": "A weekly grounding ritual that's important to her faith and community.",
        "interesting_event": "The sermon touched on a topic about believing in tiny steps with god, something she'd been wrestling with all week, which felt like perfect timing. As usual, God is always there.",
    },
    {
        "day_of_week": 6,
        "start_hour": 13,
        "name": "Lunch",
        "description": "Grabbing lunch with her cell group right after the service wraps up.",
        "location": "Café near City Harvest Church",
        "duration_hours": 1,
        "companions": "Church community and cell group",
        "reason": "A natural extension of the post-service catch-up — nobody's quite ready for the conversation to end yet.",
        "interesting_event": "Ended up in a passionate debate with Gerald over which café does the best chicken chop.",
    },
    {
        "day_of_week": 6,
        "start_hour": 14,
        "name": "Self-study",
        "description": "Doing a final round of revision to wrap up the week's coursework.",
        "location": "Home",
        "duration_hours": 3,
        "companions": "Alone",
        "reason": "Wants to start the new week with a clean slate.",
        "interesting_event": "Finally cleared the last item on her to-do list and treated herself to a snack.",
    },
    {
        "day_of_week": 6,
        "start_hour": 17,
        "name": "Texting Faith",
        "description": "Catching up with her best friend Faith over text before heading out for her evening run.",
        "location": "Home",
        "duration_hours": 1,
        "companions": "Faith (over text)",
        "reason": "Likes checking in with Faith over the weekend before the new week pulls them both back into routine.",
        "interesting_event": "They ended up trading voice notes recapping their entire weekends in painstaking detail.",
    },
    {
        "day_of_week": 6,
        "start_hour": 18,
        "name": "Evening run",
        "description": "Going for a jog around the neighbourhood to clear her head before the week ahead.",
        "location": "Punggol neighbourhood",
        "duration_hours": 1,
        "companions": "Alone",
        "reason": "Likes to squeeze in some exercise and fresh air before settling down for family dinner.",
        "interesting_event": "Took a wrong turn down an unfamiliar path and stumbled on a pretty park she never knew existed.",
    },
    {
        "day_of_week": 6,
        "start_hour": 19,
        "name": "Family dinner",
        "description": "Sharing a home-cooked dinner with her family before heading back to school.",
        "location": "Home",
        "duration_hours": 1,
        "companions": "Family",
        "reason": "Wants a proper meal with her family before the week pulls her away again.",
        "interesting_event": "Her dad told the same fishing story for what felt like the hundredth time, and everyone groaned and laughed anyway.",
    },
    {
        "day_of_week": 6,
        "start_hour": 20,
        "name": "Bus ride back to hall",
        "description": "Taking the 677 bus from Punggol back to Hall 16 to start the new week.",
        "location": "On Bus 677, heading to Hall 16",
        "duration_hours": 2,
        "companions": "Alone",
        "reason": "Needs to be back at the hall and settled in before Monday's classes begin.",
        "interesting_event": "Fell asleep on the bus and nearly missed her stop, waking up just in time.",
    },
    {
        "day_of_week": 6,
        "start_hour": 22,
        "name": "Room chores",
        "description": "Sweeping and mopping the floor, clearing out the trash, packing her cupboard, and changing into fresh bedsheets and pillow covers before the week starts.",
        "location": "Hall 16",
        "duration_hours": 2,
        "companions": "Alone",
        "reason": "Wants her room reset and tidy so she can start the week with a clear head.",
        "interesting_event": "Discovered she'd left her window open over the weekend — a thunderstorm had soaked half her floor into a small puddle, and she spent a good chunk of the two hours mopping it all up and laying towels down to dry.",
    },
]
